//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/ScriptableObjects/PlayerControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerControls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerControls"",
    ""maps"": [
        {
            ""name"": ""Player_Normal"",
            ""id"": ""4d26c3cf-df30-410e-9974-a42f5a83a504"",
            ""actions"": [
                {
                    ""name"": ""Movement"",
                    ""type"": ""Value"",
                    ""id"": ""e6bfa565-c5f6-4ee8-8438-feefe40e3e2d"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""208ff593-a76c-44c3-8efc-5ae797f5b3cb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LMB"",
                    ""type"": ""Button"",
                    ""id"": ""4c39cd6a-5fa0-4cb9-a1ba-da5419465ce0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RMB"",
                    ""type"": ""Button"",
                    ""id"": ""1db23532-5bf1-446d-b0a0-a32c8afcf3b9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MouseMovement"",
                    ""type"": ""Value"",
                    ""id"": ""4eca8691-933e-4a07-bc89-eb802ce28876"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""e6f8d2cd-bac2-4d2a-a676-94dbc050cb1d"",
                    ""path"": ""2DVector(mode=1)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""52002976-2613-40f2-b223-61dabe88b531"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""bad5b152-d876-43f4-910b-a7d70eb6ab4f"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""c4f1cf00-58e9-4576-b0b1-4278af0c6f17"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""e5baa085-0fb3-450c-b027-75e6219ee7ed"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""182709f0-a407-4c10-a8cb-459bf80c784e"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9fa53061-d00c-44cd-9764-f30a502e3fca"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LMB"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""927f1b32-78d6-46f3-9680-4d39fc9d11ca"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MouseMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""50604f3a-405b-4c05-86eb-e84703686f9d"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RMB"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Player_Normal
        m_Player_Normal = asset.FindActionMap("Player_Normal", throwIfNotFound: true);
        m_Player_Normal_Movement = m_Player_Normal.FindAction("Movement", throwIfNotFound: true);
        m_Player_Normal_Jump = m_Player_Normal.FindAction("Jump", throwIfNotFound: true);
        m_Player_Normal_LMB = m_Player_Normal.FindAction("LMB", throwIfNotFound: true);
        m_Player_Normal_RMB = m_Player_Normal.FindAction("RMB", throwIfNotFound: true);
        m_Player_Normal_MouseMovement = m_Player_Normal.FindAction("MouseMovement", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player_Normal
    private readonly InputActionMap m_Player_Normal;
    private IPlayer_NormalActions m_Player_NormalActionsCallbackInterface;
    private readonly InputAction m_Player_Normal_Movement;
    private readonly InputAction m_Player_Normal_Jump;
    private readonly InputAction m_Player_Normal_LMB;
    private readonly InputAction m_Player_Normal_RMB;
    private readonly InputAction m_Player_Normal_MouseMovement;
    public struct Player_NormalActions
    {
        private @PlayerControls m_Wrapper;
        public Player_NormalActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Movement => m_Wrapper.m_Player_Normal_Movement;
        public InputAction @Jump => m_Wrapper.m_Player_Normal_Jump;
        public InputAction @LMB => m_Wrapper.m_Player_Normal_LMB;
        public InputAction @RMB => m_Wrapper.m_Player_Normal_RMB;
        public InputAction @MouseMovement => m_Wrapper.m_Player_Normal_MouseMovement;
        public InputActionMap Get() { return m_Wrapper.m_Player_Normal; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(Player_NormalActions set) { return set.Get(); }
        public void SetCallbacks(IPlayer_NormalActions instance)
        {
            if (m_Wrapper.m_Player_NormalActionsCallbackInterface != null)
            {
                @Movement.started -= m_Wrapper.m_Player_NormalActionsCallbackInterface.OnMovement;
                @Movement.performed -= m_Wrapper.m_Player_NormalActionsCallbackInterface.OnMovement;
                @Movement.canceled -= m_Wrapper.m_Player_NormalActionsCallbackInterface.OnMovement;
                @Jump.started -= m_Wrapper.m_Player_NormalActionsCallbackInterface.OnJump;
                @Jump.performed -= m_Wrapper.m_Player_NormalActionsCallbackInterface.OnJump;
                @Jump.canceled -= m_Wrapper.m_Player_NormalActionsCallbackInterface.OnJump;
                @LMB.started -= m_Wrapper.m_Player_NormalActionsCallbackInterface.OnLMB;
                @LMB.performed -= m_Wrapper.m_Player_NormalActionsCallbackInterface.OnLMB;
                @LMB.canceled -= m_Wrapper.m_Player_NormalActionsCallbackInterface.OnLMB;
                @RMB.started -= m_Wrapper.m_Player_NormalActionsCallbackInterface.OnRMB;
                @RMB.performed -= m_Wrapper.m_Player_NormalActionsCallbackInterface.OnRMB;
                @RMB.canceled -= m_Wrapper.m_Player_NormalActionsCallbackInterface.OnRMB;
                @MouseMovement.started -= m_Wrapper.m_Player_NormalActionsCallbackInterface.OnMouseMovement;
                @MouseMovement.performed -= m_Wrapper.m_Player_NormalActionsCallbackInterface.OnMouseMovement;
                @MouseMovement.canceled -= m_Wrapper.m_Player_NormalActionsCallbackInterface.OnMouseMovement;
            }
            m_Wrapper.m_Player_NormalActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Movement.started += instance.OnMovement;
                @Movement.performed += instance.OnMovement;
                @Movement.canceled += instance.OnMovement;
                @Jump.started += instance.OnJump;
                @Jump.performed += instance.OnJump;
                @Jump.canceled += instance.OnJump;
                @LMB.started += instance.OnLMB;
                @LMB.performed += instance.OnLMB;
                @LMB.canceled += instance.OnLMB;
                @RMB.started += instance.OnRMB;
                @RMB.performed += instance.OnRMB;
                @RMB.canceled += instance.OnRMB;
                @MouseMovement.started += instance.OnMouseMovement;
                @MouseMovement.performed += instance.OnMouseMovement;
                @MouseMovement.canceled += instance.OnMouseMovement;
            }
        }
    }
    public Player_NormalActions @Player_Normal => new Player_NormalActions(this);
    public interface IPlayer_NormalActions
    {
        void OnMovement(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnLMB(InputAction.CallbackContext context);
        void OnRMB(InputAction.CallbackContext context);
        void OnMouseMovement(InputAction.CallbackContext context);
    }
}
